<a href="https://colab.research.google.com/github/HerniHartati01/Machine_Learning/blob/main/Latihan_Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Dataset
outlook=['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain']
temperature=['Hot','Hot','Mild','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Mild','Mild']
humidity=['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High']
wind=['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
outlook_encoded=le.fit_transform(outlook)
print (outlook_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
temperature_encoded=le.fit_transform(temperature)
print (temperature_encoded)

[1 1 2 2 0 0 0 2 0 2 2 2 2 2]


In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
humidity_encoded=le.fit_transform(humidity)
print (humidity_encoded)

[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [ ]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
wind_encoded=label.fit_transform(wind)
print (wind_encoded) #0 Kick 1 Punch 2 Special

play_encoded=label.fit_transform(play)
print (play_encoded) #0 Kick 1 Punch 2 Special

[1 0 1 1 1 0 0 1 1 1 0 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#Combining fitur-fitur yang ada
features=zip(outlook_encoded,temperature_encoded,humidity_encoded,wind_encoded)
features=list(features)
print (tuple(features))

((2, 1, 0, 1), (2, 1, 0, 0), (0, 2, 0, 1), (1, 2, 0, 1), (1, 0, 1, 1), (1, 0, 1, 0), (0, 0, 1, 0), (2, 2, 0, 1), (2, 0, 1, 1), (1, 2, 1, 1), (2, 2, 1, 0), (0, 2, 0, 0), (0, 2, 1, 1), (1, 2, 0, 0))


In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,play)
#Model.fit(features,label.reshape(-1,1))

#prediksi dari output
predicted = model.predict([[0,1,0,0]]) #0:Overcast 1:Hot 0:Humidity 0:Strong
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['Yes']
