<a href="https://colab.research.google.com/github/HerniHartati01/Machine_Learning/blob/main/Uas_NaiveBayes_Nmr3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Dataset
Jenis_Kelamin=['Laki-Laki', 'Laki-Laki','Perempuan','Perempuan', 'Laki-Laki', 'Laki-Laki','Perempuan','Perempuan','Laki-Laki','Prempuan']
Biaya=['murah','murah','murah','murah','murah','standar','standar','mahal','mahal','mahal']
level=['rendah','sedang','sedang','rendah','sedang','sedang','sedang','tinggi','sedang','tinggi']
transportasi=['bus','bus','kereta api','bus','bus','kereta api','kereta api','mobil','mobil','mobil']


tujuan=['No','Yes','Yes','No','Yes','No','Yes','Yes','No','No']

In [3]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
Jk_encoded=le.fit_transform(Jenis_Kelamin)
print (Jk_encoded)

[0 0 1 1 0 0 1 1 0 2]


In [4]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
biaya_encoded=le.fit_transform(Biaya)
print (biaya_encoded)

[1 1 1 1 1 2 2 0 0 0]


In [5]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
level_encoded=le.fit_transform(level)
print (level_encoded)

[0 1 1 0 1 1 1 2 1 2]


In [10]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
transportasi_encoded=label.fit_transform(transportasi)
print (transportasi_encoded) 

tujuan_encoded=label.fit_transform(tujuan)
print (tujuan_encoded) 

[0 0 1 0 0 1 1 2 2 2]
[0 1 1 0 1 0 1 1 0 0]


In [12]:
#Combining fitur-fitur yang ada
features=zip(Jk_encoded,biaya_encoded,level_encoded,transportasi_encoded)
features=list(features)
print (tuple(features))

((0, 1, 0, 0), (0, 1, 1, 0), (1, 1, 1, 1), (1, 1, 0, 0), (0, 1, 1, 0), (0, 2, 1, 1), (1, 2, 1, 1), (1, 0, 2, 2), (0, 0, 1, 2), (2, 0, 2, 2))


In [23]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,tujuan)
#Model.fit(features,label.reshape(-1,1))

#prediksi dari output
predicted = model.predict([[1,2,0,0]]) #1:perempuan 2:standar 0:rendah 0:bus
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['No']
